### ISSUE TITLE
NoMethodError: undefined method 'body'

### ISSUE THREAD

**Issue by willc0de4food** [pusher/chatkit-server-ruby#11]
Hello,

I'm trying to get this setup in my project, and when attempting to execute the code from the example, I'm getting an error: 
`NoMethodError: undefined method 'body' for {:grant_type=>"client_credentials"}:Hash`

The instance of chatkit that I instantiated appears correct, it returned an object that begins as follows:
`=> #<Chatkit::Client:0x00562df143f7b8 @api_instance=#<Pusher::Instance:0x00562df143f6f0 @service_name="chatkit", @service_version="v1", ....`

I received this error with the following code:
`chatkit.authenticate({ grant_type: "client_credentials" }, "testymctest")`

Thanks

**Comment by hamchapman** [comment]
A call to `authenticate` expects to have a request object passed in as the first parameter. For example, this is what a simple `AuthController` might look like:

```ruby
require 'chatkit'

class AuthController < ApplicationController
  skip_before_action :verify_authenticity_token

  def auth
    chatkit = Chatkit::Client.new({
      instance_locator: "YOUR_INSTANCE_LOCATOR",
      key: "YOUR_KEY"
    })

    token_json = chatkit.authenticate(request, {
      user_id: "AN_APPROPRIATE_USER_ID"
    })[:json].to_json

    render json: token_json
  end
end
```

**Comment by willc0de4food** [comment]
Thanks, that is working for me. However, when I send the response back to my app, I'm getting an error:
```
ErrorResponse {
  "headers": Object {
    "Request-Method": "SUBSCRIBE",
  },
  "info": Object {
    "error": "authentication/jwt/invalid",
    "error_description": "Could not parse the token",
  },
  "statusCode": 401,
}
```

**Comment by hamchapman** [comment]
Closing as stale.

As a side note, this will become a lost easier in the upcoming 0.7.0 release!
