### ISSUE TITLE
Documentation is wrong for send_message

### ISSUE THREAD

**Issue by cyurtbil** [pusher/chatkit-server-ruby#30]
### What?
The documentation is wrong for the send_message section of the Ruby SDK: [https://pusher.com/docs/chatkit/reference/server-ruby#send-a-message](https://pusher.com/docs/chatkit/reference/server-ruby#send-a-message)

It says that the user_id parameter should be used for sending a message but it gives an error.

### Suggested improvements
It should be sender_id instead of user_id

**Comment by vivangkumar** [comment]
Hey @cyurtbil! Thanks for noticing it and bringing this to our attention. I'll get it fixed.
