### ISSUE TITLE
Issue 

### ISSUE THREAD

**Issue by petervuoffspring** [pusher/chatkit-server-ruby#35]
### What?
When I install chatkit-server-ruby, it shows this error:
`
/home/circleci/ivy-rails/vendor/bundle/ruby/2.1.0/gems/pusher-chatkit-server-1.6.0/lib/chatkit.rb:1:in `require_relative': /home/circleci/ivy-rails/vendor/bundle/ruby/2.1.0/gems/pusher-chatkit-server-1.6.0/lib/chatkit/client.rb:694: syntax error, unexpected ':', expecting => (SyntaxError)
...e!({ headers: { "Content-Type": "application/json" } })
...                               ^
/home/circleci/ivy-rails/vendor/bundle/ruby/2.1.0/gems/pusher-chatkit-server-1.6.0/lib/chatkit/client.rb:694: syntax error, unexpected '}', expecting keyword_end
...ent-Type": "application/json" } })
...                               ^
	from /home/circleci/ivy-rails/vendor/bundle/ruby/2.1.0/gems/pusher-chatkit-server-1.6.0/lib/chatkit.rb:1:in `<top (required)>'
	from /home/circleci/ivy-rails/vendor/bundle/ruby/2.1.0/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:251:in `require'
	from /home/circleci/ivy-rails/vendor/bundle/ruby/2.1.0/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:251:in `block in require'
	from /home/circleci/ivy-rails/vendor/bundle/ruby/2.1.0/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:236:in `load_dependency'
	from /home/circleci/ivy-rails/vendor/bundle/ruby/2.1.0/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:251:in `require'
	from /home/circleci/ivy-rails/app/services/chatkit_service.rb:2:in `<class:ChatkitService>'
	from /home/circleci/ivy-rails/app/services/chatkit_service.rb:1:in `<top (required)>'
	from /home/circleci/ivy-rails/vendor/bundle/ruby/2.1.0/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:251:in `require'
	from /home/circleci/ivy-rails/vendor/bundle/ruby/2.1.0/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:251:in `block in require'
	from /home/circleci/ivy-rails/vendor/bundle/ruby/2.1.0/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:236:in `load_dependency'
	from /home/circleci/ivy-rails/vendor/bundle/ruby/2.1.0/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:251:in `require'
	from /home/circleci/ivy-rails/vendor/bundle/ruby/2.1.0/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:359:in `require_or_load'
	from /home/circleci/ivy-rails/vendor/bundle/ruby/2.1.0/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:313:in `depend_on'
	from /home/circleci/ivy-rails/vendor/bundle/ruby/2.1.0/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:225:in `require_dependency'
	from /home/circleci/ivy-rails/vendor/bundle/ruby/2.1.0/gems/railties-3.2.21/lib/rails/engine.rb:444:in `block (2 levels) in eager_load!'
	from /home/circleci/ivy-rails/vendor/bundle/ruby/2.1.0/gems/railties-3.2.21/lib/rails/engine.rb:443:in `each'
	from /home/circleci/ivy-rails/vendor/bundle/ruby/2.1.0/gems/railties-3.2.21/lib/rails/engine.rb:443:in `block in eager_load!'
	from /home/circleci/ivy-rails/vendor/bundle/ruby/2.1.0/gems/railties-3.2.21/lib/rails/engine.rb:441:in `each'
	from /home/circleci/ivy-rails/vendor/bundle/ruby/2.1.0/gems/railties-3.2.21/lib/rails/engine.rb:441:in `eager_load!'
	from /home/circleci/ivy-rails/vendor/bundle/ruby/2.1.0/gems/railties-3.2.21/lib/rails/application/finisher.rb:53:in `block in <module:Finisher>'
	from /home/circleci/ivy-rails/vendor/bundle/ruby/2.1.0/gems/railties-3.2.21/lib/rails/initializable.rb:30:in `instance_exec'
	from /home/circleci/ivy-rails/vendor/bundle/ruby/2.1.0/gems/railties-3.2.21/lib/rails/initializable.rb:30:in `run'
	from /home/circleci/ivy-rails/vendor/bundle/ruby/2.1.0/gems/railties-3.2.21/lib/rails/initializable.rb:55:in `block in run_initializers'
	from /home/circleci/ivy-rails/vendor/bundle/ruby/2.1.0/gems/railties-3.2.21/lib/rails/initializable.rb:54:in `each'
	from /home/circleci/ivy-rails/vendor/bundle/ruby/2.1.0/gems/railties-3.2.21/lib/rails/initializable.rb:54:in `run_initializers'
	from /home/circleci/ivy-rails/vendor/bundle/ruby/2.1.0/gems/railties-3.2.21/lib/rails/application.rb:136:in `initialize!'
	from /home/circleci/ivy-rails/vendor/bundle/ruby/2.1.0/gems/railties-3.2.21/lib/rails/railtie/configurable.rb:30:in `method_missing'
	from /home/circleci/ivy-rails/config/environment.rb:5:in `<top (required)>'
	from /home/circleci/ivy-rails/spec/spec_helper.rb:34:in `require'
	from /home/circleci/ivy-rails/spec/spec_helper.rb:34:in `<top (required)>'
	from /home/circleci/ivy-rails/vendor/bundle/ruby/2.1.0/gems/rspec-core-2.14.7/lib/rspec/core/configuration.rb:867:in `require'
	from /home/circleci/ivy-rails/vendor/bundle/ruby/2.1.0/gems/rspec-core-2.14.7/lib/rspec/core/configuration.rb:867:in `block in setup_load_path_and_require'
	from /home/circleci/ivy-rails/vendor/bundle/ruby/2.1.0/gems/rspec-core-2.14.7/lib/rspec/core/configuration.rb:867:in `each'
	from /home/circleci/ivy-rails/vendor/bundle/ruby/2.1.0/gems/rspec-core-2.14.7/lib/rspec/core/configuration.rb:867:in `setup_load_path_and_require'
	from /home/circleci/ivy-rails/vendor/bundle/ruby/2.1.0/gems/rspec-core-2.14.7/lib/rspec/core/configuration_options.rb:25:in `configure'
	from /home/circleci/ivy-rails/vendor/bundle/ruby/2.1.0/gems/rspec-core-2.14.7/lib/rspec/core/command_line.rb:21:in `run'
	from /home/circleci/ivy-rails/vendor/bundle/ruby/2.1.0/gems/rspec-core-2.14.7/lib/rspec/core/runner.rb:80:in `run'
	from /home/circleci/ivy-rails/vendor/bundle/ruby/2.1.0/gems/rspec-core-2.14.7/lib/rspec/core/runner.rb:17:in `block in autorun'
`
My stack are:
- ruby: **2.1.0**
- rails: **3.2.21**
- pusher-chatkit-server: **1.6.0**

### Suggested improvements
I go to file `vendor/bundle/ruby/2.1.0/gems/pusher-chatkit-server-1.6.0/lib/chatkit/client.rb` line `694` and update 
`options.merge!({ headers: { "Content-Type" : "application/json" } })` 
to 
`options.merge!({ headers: { "Content-Type" => "application/json" } })` 
and it worked. Can you guys fix it pls.

**Comment by luismfonseca** [comment]
Fixed in 1.7.1.

Thanks for reporting!
