### ISSUE TITLE
Ruby Package License Info

### ISSUE THREAD

**Issue by AlexArendsen** [pusher/chatkit-server-ruby#8]
Hi devs! I'm planning on trying out Chatkit for my CS capstone project, and would like to know if your Ruby package is licensed under the MIT license like your other Chatkit components. I couldn't find a `LICENSE.md` file in this repo, so I thought I'd ask here to be safe.

**Comment by hamchapman** [comment]
I will add an MIT `LICENCE.md` to the repo now 👍

**Comment by hamchapman** [comment]
Done!

**Comment by hamchapman** [comment]
And let me know if you hit any problems or need any help!

**Comment by AlexArendsen** [comment]
Awesome, I certainly will. Thanks much!
