### ISSUE TITLE
Missing comma in client.rb

### ISSUE THREAD

**Issue by shaunjacobsen** [pusher/chatkit-server-ruby#9]
I installed the gem per the [instructions](https://docs.pusher.com/chatkit/reference/server-ruby) using bundler:

`gem 'pusher-chatkit-server'`

`bundle install`

Then added `require 'chatkit'` in my app. Tried to start the server with `rackup` and could not do so. I traced the error back to a missing comma on line 219 of /lib/chatkit/client.rb:

![capture d ecran 2017-12-01 a 17 10 20](https://user-images.githubusercontent.com/734057/33507569-0bcd112c-d6bb-11e7-8c95-3b7af09ac930.png)

**Comment by hamchapman** [comment]
Good spot and sorry about that! I'll push up a new version with a fix now 👍

**Comment by hamchapman** [comment]
Just published 0.4.1 which fixes this! Thanks again!
